name: Hexo Build And Publish
on:
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Hexo-cli
        run: |
          npm -v 
          npm install -g hexo-cli
          hexo -v
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT }}
      - name: Build
        run: |
          cd hexo
          npm install
          hexo g  
