name: Hexo Build And Publish
on:
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache node modules
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Hexo-cli
        
        run: |
          npm -v 
          npm install -g hexo-cli
          hexo -v
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT }}
      - name: Build
        run: |
          #cd hexo
          npm install
          hexo g
      - name: Package
        run: |
          tar -czvf pubilc.tar public
          speed 3s
          mv pubilc.tar $GITHUB_WORKSPACE/

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: public.tar
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
          release_name: ${{env.strDate}}
